name: Update Leaderboard

on:
  push:
    branches: [ main ]

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write   # IMPORTANT

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install pandas

      - name: Update leaderboard
        run: python update_leaderboard.py

      - name: Commit changes
        run: |
          git config --global user.name "leaderboard-bot"
          git config --global user.email "bot@example.com"
          git add docs/leaderboard.csv
          git commit -m "Auto update leaderboard" || echo "No changes"
          git push
