name: Validate Submission

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  test-submission:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install requirements
        run: |
          pip install -r requirements.txt

      - name: Run grader
        run: |
          python .github/scripts/process_submission.py
